spring:
  profiles:
      active: dev #现在激活的是开发环境
---
spring:
  profiles: dev #开发环境
  application:
       name: microservicecloud-config-sxt-dev
---
spring:
  profiles: test #测试环境
  application:
      name: microservicecloud-config-sxt-test
